<?
/////////////////////////////////////////////////////////////////////////////////////////
$RFS_THEME_TOP_MENU_LOCATION="top";
$RFS_THEME_NAV_FONT="ALIENSAT.TTF";
$RFS_THEME_NAV_IMG=1;
$RFS_THEME_NAV_FONT_COLOR="#FF0000";
$RFS_THEME_NAV_FONT_BGCOLOR="#442200";
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_FONT="ALIENSAT.TTF";
$RFS_THEME_TTF_TOP_FONT_SIZE="45";
$RFS_THEME_TTF_TOP_COLOR="#FF0000";
$RFS_THEME_TTF_TOP_BGCOLOR="#442200";
$RFS_THEME_NAV_FONT_Y_OFFSET="-8";
$RFS_THEME_TTF_TOP_FONT_Y_OFFSET="-20";

?>
