<?
/////////////////////////////////////////////////////////////////////////////////////////
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="ALIENSAT.TTF";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="ALIENSAT.TTF";
$RFS_SITE_NAV_FONT_COLOR="#aa9900";
$RFS_SITE_NAV_FONT_BGCOLOR="#442200";
?>