<?

//$RFS_THEME_TOP_MENU_LOCATION="top";
//$RFS_THEME_NAV_IMG_TOP="1";
//$RFS_THEME_NAV_FONT="Crumb.ttf";
//$RFS_THEME_NAV_IMG=1;
//$RFS_THEME_NAV_FONT_COLOR="#01ff00";
//$RFS_THEME_NAV_FONT_BGCOLOR="#330000";
//$RFS_THEME_NAV_FONT_Y_OFFSET="-4";
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_FONT="sketch-block.ttf";
$RFS_THEME_TTF_TOP_COLOR="#888888";//"#ffbb70";
$RFS_THEME_TTF_TOP_BGCOLOR="#222222";
$RFS_THEME_TTF_TOP_FONT_SIZE="45";
$RFS_THEME_TTF_TOP_FONT_Y_OFFSET="-20";
$RFS_THEME_TTF_TOP_FONT_X_OFFSET="5";

?>
