<?
$title="My Bullets";
chdir("../../");
include("header.php");

function bullet_buttons() { eval(lib_rfs_get_globals());
	
	echo "<hr>";	
	lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=edit_bullets","My Bullets");
	lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=short_list","Brief List");
	lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=epr_format","Format for EPR");
	
	lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=send_report","Send Bullets to Supervisor");
	
	if(lib_access_check("bullet_log","admin")) {
		lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=edit_categories","Edit Categories");
	}
}

function bullet_log_action_send_report_go() {	eval(lib_rfs_get_globals());
	echo "<h1>Send My Bullets to Supervisor</h1>";
	bullet_buttons();
	echo "<hr>";
	echo "Sending report to $email<hr>";

	$subject="$data->name bullets";
	
	$message ="This report was generated by 3dnetlabs.info.<br>\n";
	$message.="$data->name requested to send you a bullets report.<br>\n";
	$message.="<hr>\n";
	$message.="<div style=\"font-face: Times New Roman; font-size: 12px;\">";
	$r=lib_mysql_query("select * from `rfsm_bullet_log` where `username`='$data->name'");
	for($i=0;$i<mysql_num_rows($r);$i++) {
		$bullet=mysql_fetch_object($r);
		$message.=" - $bullet->what; $bullet->how; $bullet->impact<br>";
	}
	$message.="</div>";
	echo "$subject<hr>$message";
	mailgo($email,$message,$subject);
}

function bullet_log_action_send_report() { eval(lib_rfs_get_globals());
	echo "<h1>Send My Bullets to Supervisor</h1>";
	bullet_buttons();
	echo "<hr>";
	
	echo "<form action=\"$RFS_SITE_URL/modules/bullet_log/bullet_log.php\" method=\"POST\">";
	echo "Supervisor's Email: <input name=\"email\" value=\"\">";
	lib_mysql_hidden_var("action","send_report_go");
	echo "<input type=\"submit\" value=\"Send\">";
	echo "</form>";
	
}

function bullet_log_action_change_category_image() { eval(lib_rfs_get_globals());
	$page ="$RFS_SITE_URL/include/lib.mysql.php?act=select_image_chdir&";
	$page.="rtnpage=modules/bullet_log/bullet_log.php&";
	$page.="rtnact=edit_categories&";
	$page.="id=$bcid&";
	$page.="npath=icons&";
	$page.="table=rfsm_bullet_category&";
	$page.="image_field=image&";
	$page.="spath=$RFS_SITE_PATH";
	lib_domain_gotopage($page);
}

function bullet_log_action_edit_categories() { eval(lib_rfs_get_globals());
	echo "<h1>Edit Bullet Categories</h1>";
	$r=lib_mysql_query("select * from rfsm_bullet_category");
	$x=mysql_num_rows($r);
	for($i=0;$i<$x;$i++) {
		$bcat=mysql_fetch_object($r);
		
		if(empty($bcat->image)) $bcat->image="$RFS_SITE_URL/images/icons/noimage.gif";
		
		echo " $bcat->name <br>
				<a href=\"$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=change_category_image&bcid=$bcat->id\"><img src=\"$bcat->image\" width=32></a> <BR>";
	}
	
}

function bullet_log_action_share_go() { eval(lib_rfs_get_globals());
	$bullet=lib_mysql_fetch_one_object("select * from rfsm_bullet_log where id='$bullet'");	
	echo "<h1>Sharing bullet ($bullet->id) $bullet->name</h1>";
	bullet_buttons();
	echo "<hr>";
	echo "Cloning this bullet to user $share_user<br>";

	lib_mysql_query("insert into `rfsm_bullet_log` (`name`) values ('$bullet->name');");
	$id=mysql_insert_id();
	echo "NEW BULLET IS $id<br>";
	lib_mysql_query("update `rfsm_bullet_log` set `category` = '$bullet->category' where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `what`     = '$bullet->what'     where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `when`     = '$bullet->when'     where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `how`      = '$bullet->how'      where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `impact`   = '$bullet->impact'   where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `other`    = '$bullet->other'    where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `date`     = '$bullet->date'     where `id`='$id'");	
	lib_mysql_query("update `rfsm_bullet_log` set `username` = '$share_user'       where `id`='$id'");
	lib_mysql_query("update `rfsm_bullet_log` set `shared`   = '$data->name'       where `id`='$id'");
		
	$userdata=lib_users_get_data($share_user);
	echo "$userdata->name : $userdata->email <br>";
	
	$subject = "$data->name shared a bullet with you.";
	$message = "$data->name has shared a bullet with you on 3dnetlabs.info<br>";
	$message.= "<hr>";
	$message.= "BULLET: $bullet->name<br>";
	$message.= "$bullet->what ; $bullet->how ; $bullet->impact<br>";
	$message.= "<hr>Login <a href=\"$RFS_SITE_URL\">$RFS_SITE_URL</a> to view and modify your bullets.<br>";
		
	mailgo(	$userdata->email,
				$message,
				$subject);
	
	echo "<hr>";
	
}

function bullet_log_action_share_bullet() { eval(lib_rfs_get_globals());
	echo "<h1>Share Bullet</h1>";
	bullet_buttons();
	echo "<hr>";
	$bullet=lib_mysql_fetch_one_object("select * from rfsm_bullet_log where id=$bid");
	lib_forms_warn("Share bullet: <br> $bullet->name $bullet->what $bullet->how $bullet->impact
							<br>
							<br>
				");
	
	echo "<form action=\"$RFS_SITE_URL/modules/bullet_log/bullet_log.php\" method=\"POST\">";
	
	echo "<select name=\"share_user\"><option>Select recipient for this bullet";
	$res=lib_mysql_query("select * from `users` order by  `name` asc");
	$count=mysql_num_rows($res);
	for($i=0;$i<$count;$i++)	{
			$userdata=mysql_fetch_object($res);
    		echo "<option>$userdata->name";
    }
	echo "</select><br>";
	echo "<input type=\"submit\" name=\"submit\" value=\"Share\">";
	lib_mysql_hidden_var("action","share_go");
	lib_mysql_hidden_var("bullet","$bullet->id");
	echo "</form>";
	include("footer.php");
}

function bullet_log_action_add_bullet_go() { eval(lib_rfs_get_globals());
	echo "<h1>Update Bullet</h1>";	
	
	$name=addslashes($name);
	lib_mysql_query("update `rfsm_bullet_log` set `name`     = '$name'     where `id`='$bid'");
	$what=addslashes($what);
	lib_mysql_query("update `rfsm_bullet_log` set `what`     = '$what'     where `id`='$bid'");
	$how=addslashes($how);
	lib_mysql_query("update `rfsm_bullet_log` set `how`      = '$how'      where `id`='$bid'");
	$impact=addslashes($impact);
	lib_mysql_query("update `rfsm_bullet_log` set `impact`   = '$impact'   where `id`='$bid'");	
	$other=addslashes($other);
	lib_mysql_query("update `rfsm_bullet_log` set `other` 	 = '$other' 	 where `id`='$bid'");
	$date=addslashes($_REQUEST['date']);
	lib_mysql_query("update `rfsm_bullet_log` set `date` 	 = '$date'     where `id`='$bid'");
	if( (empty($category)) || ($category=="Select Category")) {
		$category="Job Related";
	}	
	lib_mysql_query("update `rfsm_bullet_log` set `category` = '$category' where `id`='$bid'");
	echo "Bullet updated.<br>";	
	lib_domain_gotopage("$RFS_SITE_URL/modules/bullet_log/bullet_log.php");
	include("footer.php");
}

function bullet_log_action_edit_bullet() { eval(lib_rfs_get_globals());
	echo "<h1>Edit Bullet</h1>";
	bullet_buttons();
	echo "<hr>";
	echo "<div class=\"forum_box\">";
	$ncat="Select Category";
	$bcat=lib_mysql_fetch_one_object("select * from `rfsm_bullet_log` where id='$bid'");
	if(!empty($bcat->category)) $ncat=$bcat->category;
	lib_forms_build( "$RFS_SITE_URL/modules/bullet_log/bullet_log.php",
	       "action=add_bullet_go".$RFS_SITE_DELIMITER.
			"SHOW_SELECTOR_rfsm_bullet_category#name#category#$ncat".$RFS_SITE_DELIMITER.
		    "bid=$bid",		   
	       "rfsm_bullet_log", "select * from `rfsm_bullet_log` where `id`='$bid'",
	       "id".$RFS_SITE_DELIMITER.
		    "username".$RFS_SITE_DELIMITER.
		    "when".$RFS_SITE_DELIMITER."category",
		    "shared","omit","",100,"Go" );
	echo "</div>";
	include("footer.php");	
}

function bullet_log_action_add_bullet() { eval(lib_rfs_get_globals());
	echo "<h1>Add New Bullet</h1>";
	echo $bullet;
	lib_mysql_query("insert into rfsm_bullet_log (`name`,`username`) 
										VALUES('$bullet','$data->name');");
	global $bid;
	$bid=mysql_insert_id();
	bullet_log_action_edit_bullet();
}

function bullet_log_action_f_delete_bullet_go () { eval(lib_rfs_get_globals());
	echo "<h1>Delete Bullet</h1>";
	lib_mysql_query("delete from rfsm_bullet_log where id='$bid'");
	echo "Bullet deleted.<br>";
	lib_domain_gotopage("$RFS_SITE_URL/modules/bullet_log/bullet_log.php");	
	include("footer.php");
}
 
function bullet_log_action_delete_bullet() { eval(lib_rfs_get_globals());
	echo "<h1>Delete Bullet</h1>";
	$bullet=lib_mysql_fetch_one_object("select * from rfsm_bullet_log where id=$bid");
	lib_forms_confirm(	"Are you sure you want to delete this bullet:<br><hr>$bullet->name $bullet->what $bullet->how $bullet->impact $bullet->category ? <br>
						<hr>WARNING: This can not be undone.",
						"$RFS_SITE_URL/modules/bullet_log/bullet_log.php",
						"action=f_delete_bullet_go".$RFS_SITE_DELIMITER."bid=$bullet->id" );
	include("footer.php");
}

function bullet_log_action_edit_bullets() { eval(lib_rfs_get_globals());
	echo "<h1>Edit My Bullets</h1>";
	bullet_buttons();	
	echo "<hr>";
	
	echo "<div class=\"forum_box\">";
	echo "<h2>Add a New Bullet</h2>";
	lib_forms_build( "$RFS_SITE_URL/modules/bullet_log/bullet_log.php",
	       "action=add_bullet".$RFS_SITE_DELIMITER.	       
	       "SHOW_CLEARFOCUSTEXT_50#50#bullet=Enter bullet name",
	       "","","","","","",50,"New Bullet" );
	echo "</div>";		

	echo "<hr>";			   
	$r=lib_mysql_query("select * from `rfsm_bullet_log` where `username`='$data->name' order by `when` desc");
	$x=mysql_num_rows($r);
	if($x) {
		for($i=0;$i<$x;$i++) {
			$bullet=mysql_fetch_object($r);			
			if(!empty($bullet->name))  {
				echo "<div class=\"forum_box\">";
					echo "<h2>$bullet->name</h2>";
					echo "<div class=\"forum_user\">";
					lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=edit_bullet&bid=$bullet->id","Edit");
					echo "<br>";
					lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=delete_bullet&bid=$bullet->id","Delete");
					echo "<br>";
					lib_button("$RFS_SITE_URL/modules/bullet_log/bullet_log.php?action=share_bullet&bid=$bullet->id","Share");
					echo "</div>";
					echo "<div class=\"forum_message\">";
					echo "CREATED: $bullet->when<br>";
					echo "CATEGORY: $bullet->category<br>";
					echo "<hr>";
					echo "DATE: $bullet->date<br>";					
					echo "WHAT: $bullet->what<br>";
					echo "HOW: $bullet->how<br>";
					echo "IMPACT: $bullet->impact <br>";
					echo "<hr>";
					echo " - $bullet->what;  $bullet->how;  $bullet->impact<br>";
					
					if(!empty($bullet->other)) {
						echo "<hr>";
						echo "OTHER: $bullet->other <br>";						
					}
					
					if(!empty($bullet->shared)) {
						echo "<hr>";
						echo "SHARED BY: $bullet->shared <br>";
					
					}
					
					echo "</div>";					
				echo "</div>";
			}
		}
	}
	else {
		echo "No bullets yet.<br>";
	}
	include("footer.php");
}

function bullet_log_action_epr_format() { eval(lib_rfs_get_globals());
	echo "<h1>Bullets in EPR Format</h1>";
	bullet_buttons();
	echo "<hr>";

	echo "<textarea
			rows=40 
			style='font-family: Times New Roman;
					font-size: 12px;
					min-width:590px;					
					width: 590px; '>";	
					
	echo "NOTE: THIS TEXT AREA IS THE APPROXIMATE WIDTH OF THE ELECTRONIC EPR FORM.\n";
	echo "The font used is Times New Roman 12\n";
	echo "===================================================================================\n";
	
	$r=lib_mysql_query("select * from `rfsm_bullet_log` where `username`='$data->name' 
	and category ='Job Related'
	order by `when` desc");
	echo "JOB RELATED:\n";
	$x=mysql_num_rows($r);
	for($i=0;$i<$x;$i++) {
		$bullet=mysql_fetch_object($r);
		echo " - $bullet->what; $bullet->how; $bullet->impact\n";
	}
	
	$r=lib_mysql_query("select * from `rfsm_bullet_log` where `username`='$data->name' 
	and category ='Volunteer'
	order by `when` desc");
	echo "VOLUNTEER:\n";
	$x=mysql_num_rows($r);
	for($i=0;$i<$x;$i++) {
		$bullet=mysql_fetch_object($r);
		echo " - $bullet->what; $bullet->how; $bullet->impact\n";
	}
	
	$r=lib_mysql_query("select * from `rfsm_bullet_log` where `username`='$data->name' 
	and category ='Self Improvement'
	order by `when` desc");
	echo "SELF IMPROVEMENT:\n";
	$x=mysql_num_rows($r);
	for($i=0;$i<$x;$i++) {
		$bullet=mysql_fetch_object($r);
		echo " - $bullet->what; $bullet->how; $bullet->impact\n";
	}
	
	
		
	echo "</textarea>";

	include("footer.php");

}

function bullet_log_action_short_list() { eval(lib_rfs_get_globals());
	echo "<h1>Brief listing</h1>";
	bullet_buttons();
	echo "<hr>";
	module_bullet_log_long(10000); 
}

function bullet_log_action_() { eval(lib_rfs_get_globals());
	bullet_log_action_edit_bullets();
	include("footer.php");
}



?>

