<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="Berthside.ttf";
$RFS_SITE_NAV_IMG="1";

$RFS_SITE_NAV_FONT_COLOR="#ffee00";
$RFS_SITE_NAV_FONT_BGCOLOR="#442200";
$RFSW_BULLET_IMAGE=$RFS_SITE_URL."/images/navigation/bullet1.gif";
$RFS_SITE_NAV_FONT_Y_OFFSET="-8";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_COLOR="C48D2A";




$RFS_SITE_TTF_TOP_BGCOLOR="141A1F";


$RFS_SITE_TTF_TOP_FONT="Pecot012.ttf";
$RFS_SITE_TTF_TOP_FONT_SIZE="35";
?>
