<?
$RFS_SITE_TOP_MENU_LOCATION="top";

$RFS_SITE_NAV_FONT="8bitlimr.ttf";
$RFS_SITE_NAV_FONT_SIZE=25;
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_NAV_FONT_COLOR		="#FFFFFF";
$RFS_SITE_NAV_FONT_BGCOLOR	="#3a3a3a";


$RFS_SITE_TTF_TOP_FONT="8bitlimr.ttf";
$RFS_SITE_TTF_TOP_FONT_SIZE=65;
$RFS_SITE_TTF_TOP=1;
$RFS_SITE_TTF_TOP_COLOR="#009F00";
$RFS_SITE_TTF_TOP_BGCOLOR="#000000";


$RFSW_BULLET_IMAGE = $RFS_SITE_URL."/modules/wiki/images/bullet.gif";
$RFSW_LINK_IMAGE   = $RFS_SITE_URL."/modules/wiki/images/link.png";



?>
