<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="8bitlimr.ttf";
$RFS_SITE_NAV_FONT_SIZE="25";
$RFS_SITE_NAV_IMG="1";
$RFS_SITE_NAV_FONT_COLOR="#FF0000";
$RFS_SITE_NAV_FONT_BGCOLOR="#333333";
$RFS_SITE_TTF_TOP_FONT="underscr.ttf";
$RFS_SITE_TTF_TOP_FONT_SIZE="65";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_COLOR="#FF0000";
$RFS_SITE_TTF_TOP_BGCOLOR="#333333";
$RFSW_BULLET_IMAGE = "$RFS_SITE_URL/modules/wiki/images/bullet.gif";
$RFSW_LINK_IMAGE   = "$RFS_SITE_URL/modules/wiki/images/link.png";
$RFS_SITE_NAV_FONT_Y_OFFSET="-5";
?>