<?
$RFS_SITE_NAV_FONT_SIZE="15";

$RFS_SITE_NAV_IMG="1";

$RFS_SITE_TTF_TOP_FONT_SIZE="66";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_COLOR="C4BDC7";



$RFS_SITE_TTF_TOP_BGCOLOR="#333333";
$RFSW_BULLET_IMAGE = "$RFS_SITE_URL/modules/wiki/images/bullet.gif";
$RFSW_LINK_IMAGE   = "$RFS_SITE_URL/modules/wiki/images/link.png";
$RFS_SITE_NAV_FONT_Y_OFFSET="-5";
$RFS_SITE_NAV_FONT_BGCOLOR="101703";
$RFS_SITE_NAV_FONT="8bitlimr.ttf";


$RFS_SITE_TTF_TOP_FONT="underscr.ttf";

$RFS_SITE_NAV_FONT_COLOR="C2BAC2";




?>
