<?
$RFS_SITE_SINGLETABLEWIDTH=940;
$RFS_SITE_THEME_DROPDOWN=true;
$RFS_SITE_NAV_FONT= "impact.ttf";
$RFS_SITE_NAV_FONT_COLOR = "#7171ff";
$RFS_SITE_NAV_FONT_BGCOLOR = "#010000";
$RFS_SITE_TTF_TOP_FONT_SIZE=45;
$RFS_SITE_TTF_TOP_FONT_X_OFFSET="0";
$RFS_SITE_TTF_TOP_FONT_Y_OFFSET="15";
$RFS_SITE_TTF_TOP_FONT="Crumb.ttf";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_COLOR="#7171ff";
$RFS_SITE_TTF_TOP_BGCOLOR="#010000";
$RFS_SITE_NAV_BUTTONS="1";
?>