<?
$RFS_THEME_SINGLETABLEWIDTH=940;
$RFS_THEME_THEME_DROPDOWN=true;
$RFS_THEME_NAV_FONT= "impact.ttf";
$RFS_THEME_NAV_FONT_COLOR = "#7171ff";
$RFS_THEME_NAV_FONT_BGCOLOR = "#010000";
$RFS_THEME_TTF_TOP_FONT_SIZE=45;
$RFS_THEME_TTF_TOP_FONT_X_OFFSET="0";
$RFS_THEME_TTF_TOP_FONT="Crumb.ttf";
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_COLOR="#7171ff";
$RFS_THEME_TTF_TOP_BGCOLOR="#010000";
?>