<?
// LOAD VARIABLE DEFAULTS

$RFS_SITE_SINGLETABLEWIDTH=940;
$RFS_SITE_DOUBLETABLEWIDTH=435;
$RFS_SITE_THEME_DROPDOWN=true;

$RFS_SITE_NAV_FONT	= "Impact.ttf";
$RFS_SITE_NAV_FONT_BGCOLOR = "#000000";
$RFS_SITE_NAV_FONT_COLOR = "#0000FF";

?>
