<?
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_FONT="BaroqueAntiqueScript.ttf";
$RFS_THEME_TTF_TOP_COLOR="#FFcccc";
$RFS_THEME_TTF_TOP_BGCOLOR="#DD9999";
$RFS_THEME_TTF_TOP_FONT_SIZE="35";
$RFS_THEME_TTF_TOP_FONT_X_OFFSET="0";
$RFS_THEME_NAV_IMG="1";
$RFS_THEME_NAV_FONT="consolaz.ttf";
$RFS_THEME_NAV_FONT_COLOR="#ffcccc";
$RFS_THEME_NAV_FONT_BGCOLOR="#997777";
$RFS_THEME_TTF_TOP_FONT_Y_OFFSET="-25";

?>
