<?

$RFS_SITE_BODY_CLOSE="<p>&nbsp;</p></body>";
$RFS_SITE_HTML_CLOSE="</html>";

$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_FONT="Achafsex.ttf";
$RFS_SITE_TTF_TOP_COLOR="#FF9999";
$RFS_SITE_TTF_TOP_BGCOLOR="#000000";
$RFS_SITE_TTF_TOP_FONT_SIZE="45";
$RFS_SITE_TTF_TOP_FONT_Y_OFFSET="-15";
$RFS_SITE_TTF_TOP_FONT_X_OFFSET="0";
?>