<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="MagicLanternNF.ttf";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="MagicLanternNF.ttf";
$RFS_SITE_NAV_FONT_COLOR="#FF9F5F";
$RFS_SITE_NAV_FONT_BGCOLOR="#5a3a0f";
?>

