<?
$RFS_THEME_TOP_MENU_LOCATION="top";
$RFS_THEME_NAV_FONT="MagicLanternNF.ttf";
$RFS_THEME_NAV_IMG=1;
$RFS_THEME_FONT="MagicLanternNF.ttf";
$RFS_THEME_NAV_FONT_COLOR="#FF9F5F";
$RFS_THEME_NAV_FONT_BGCOLOR="#5a3a0f";
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_FONT="MagicLanternNF.ttf";
$RFS_THEME_TTF_TOP_COLOR="#FF9F5F";
$RFS_THEME_TTF_TOP_BGCOLOR="#5A3A0F";
$RFS_THEME_TTF_TOP_FONT_SIZE="40";
$RFS_THEME_TTF_TOP_FONT_X_OFFSET="0";

?>