<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="MagicLanternNF.ttf";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="MagicLanternNF.ttf";
$RFS_SITE_NAV_FONT_COLOR="#FF9F5F";
$RFS_SITE_NAV_FONT_BGCOLOR="#5a3a0f";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_FONT="MagicLanternNF.ttf";
$RFS_SITE_TTF_TOP_COLOR="#FF9F5F";
$RFS_SITE_TTF_TOP_BGCOLOR="#5A3A0F";
$RFS_SITE_TTF_TOP_FONT_SIZE="40";
$RFS_SITE_TTF_TOP_FONT_X_OFFSET="0";
$RFS_SITE_TTF_TOP_FONT_Y_OFFSET="10";

?>