<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="Crumb.ttf";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_NAV_FONT_COLOR="#01ff00";
$RFS_SITE_NAV_FONT_BGCOLOR="303328";

$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_FONT="Crumb.ttf";
$RFS_SITE_TTF_TOP_COLOR="#01FF00";
$RFS_SITE_TTF_TOP_BGCOLOR="303327";

$RFS_SITE_TTF_TOP_FONT_SIZE="45";
$RFS_SITE_NAV_FONT_Y_OFFSET="-4";



?>