<?
/////////////////////////////////////////////////////////////////////////////////////////
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="ArcadeClassic.ttf";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="ArcadeClassic.ttf";
$RFS_SITE_NAV_FONT_COLOR="#A397FF";
$RFS_SITE_NAV_FONT_BGCOLOR="#4D44DB";
?>
