<?php
/////////////////////////////////////////////////////////////////////////////////////////
// RFSCMS http://www.sethcoder.com/
/////////////////////////////////////////////////////////////////////////////////////////
$this_dir=getcwd();
require_once("session.php");
require_once("lib.div.php");
require_once("lib.log.php");
require_once("version.php");
require_once("lib.debug.php");
require_once("lib.access.php");
require_once("lib.mysql.php");
require_once("lib.string.php");
require_once("lib.file.php");
require_once("lib.flash.php");
require_once("lib.ajax.php");
require_once("lib.users.php");
require_once("lib.sitevars.php");
require_once("lib.helpers.php");
require_once("lib.forms.php");
require_once("lib.rfs.php");
require_once("lib.paypal.php");
require_once("lib.social.php");
require_once("lib.domain.php");
require_once("lib.menus.php");
require_once("lib.themes.php");
require_once("lib.buttons.php");
require_once("lib.images.php");
require_once("lib.genm.php");
require_once("lib.network.php");
require_once("lib.modules.php");
require_once("lib.tags.php");
/////////////////////////////////////////////////////////////////////////////////////////
if(isset($_SESSION['valid_user']))
$data=lib_users_get_data($_SESSION['valid_user']);
/////////////////////////////////////////////////////////////////////////////////////////
