<?
/////////////////////////////////////////////////////////////////////////////////////////
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="FORCE3.TTF";
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="_44v2e.ttf";
$RFS_SITE_NAV_FONT_COLOR="#aa9900";
$RFS_SITE_NAV_FONT_BGCOLOR="#442200";
?>