<?php
$RFS_THEME_TOP_MENU_LOCATION="top";
$RFS_THEME_NAV_FONT="FORCE3.TTF";
$RFS_THEME_NAV_FONT_SIZE=12;
$RFS_THEME_NAV_FONT_X_OFFSET=0;
$RFS_THEME_NAV_FONT_Y_OFFSET=-8;
$RFS_THEME_NAV_IMG=1;
$RFS_THEME_NAV_FONT_COLOR="#ff9900";
$RFS_THEME_NAV_FONT_BGCOLOR="#550000";
$RFS_THEME_TTF_TOP_FONT="AristotlePunk.ttf";


$RFS_THEME_TTF_TOP_FONT_SIZE="65";

$RFS_THEME_TTF_TOP_FONT_X_OFFSET="25";



$RFS_THEME_TTF_TOP=1;
$RFS_THEME_TTF_TOP_COLOR="#ff9900";
$RFS_THEME_TTF_TOP_BGCOLOR="#331100";
$RFS_THEME_TTF_TOP_FONT_Y_OFFSET="-25";

?>
