<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="PushBlack.ttf";
$RFS_SITE_NAV_FONT_SIZE=15;
$RFS_SITE_NAV_IMG=1;
$RFS_SITE_FONT="Alphav2.ttf";
$RFS_SITE_NAV_FONT_COLOR="#FFFFFF";
$RFS_SITE_NAV_FONT_BGCOLOR="#3a3a3a";
?>

