<?
$RFS_THEME_TOP_MENU_LOCATION="top";
$RFS_THEME_NAV_FONT="DisposableDroidBB_bldital.ttf";
$RFS_THEME_NAV_FONT_SIZE="25";
$RFS_THEME_NAV_IMG="1";
$RFS_THEME_NAV_FONT_COLOR="#FFFFFF";
$RFS_THEME_NAV_FONT_BGCOLOR="#7a7a7a";
$RFS_THEME_TTF_TOP_FONT="underscr.ttf";
$RFS_THEME_TTF_TOP_FONT_SIZE="45";
$RFS_THEME_TTF_TOP="1";
$RFS_THEME_TTF_TOP_COLOR="#81aef1";
$RFS_THEME_TTF_TOP_BGCOLOR="#7a7a7a";
$RFS_THEME_TTF_TOP_FONT_Y_OFFSET="-10";

$RFSW_BULLET_IMAGE="$RFS_THEME_URL/modules/wiki/images/bullet.gif";
$RFSW_LINK_IMAGE="$RFS_THEME_URL/modules/wiki/images/link.png";
$RFS_THEME_NAV_FONT_Y_OFFSET="-8";


?>
