<?
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT="DisposableDroidBB_bldital.ttf";

$RFS_SITE_NAV_FONT_SIZE="25";
$RFS_SITE_NAV_IMG="1";
$RFS_SITE_NAV_FONT_COLOR="DFFFC9";


$RFS_SITE_NAV_FONT_BGCOLOR="000000";

$RFS_SITE_TTF_TOP_FONT="DisposableDroidBB_bldital.ttf";
$RFS_SITE_TTF_TOP_FONT_SIZE="45";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_TTF_TOP_COLOR="DFFFC9";


$RFS_SITE_TTF_TOP_BGCOLOR="030303";

$RFS_SITE_TTF_TOP_FONT_Y_OFFSET="-10";

$RFSW_BULLET_IMAGE="$RFS_SITE_URL/modules/wiki/images/bullet.gif";
$RFSW_LINK_IMAGE="$RFS_SITE_URL/modules/wiki/images/link.png";
$RFS_SITE_NAV_FONT_Y_OFFSET="-8";

?>

