<?
/////////////////////////////////////////////////////////////////////////////////////////
$RFS_SITE_TOP_MENU_LOCATION="top";
$RFS_SITE_NAV_FONT_COLOR="#55FF00";
$RFS_SITE_NAV_FONT_BGCOLOR="#114400";
$RFS_SITE_TTF_TOP_COLOR="#55aa00";
$RFS_SITE_TTF_TOP_BGCOLOR="#114400";
$RFS_SITE_TTF_TOP_FONT_SIZE="35";

$RFS_SITE_TTF_TOP_FONT_X_OFFSET="0";
$RFS_SITE_TTF_TOP_FONT_Y_OFFSET="8";



$RFS_SITE_NAV_FONT_SIZE="12";
$RFS_SITE_TTF_TOP_FONT="BurntMF.ttf";
$RFS_SITE_TTF_TOP="1";
$RFS_SITE_NAV_FONT="BurntMF.ttf";
$RFS_SITE_NAV_FONT_Y_OFFSET="-3";
$RFS_SITE_NAV_IMG="1";
?>
